import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Wraper from "@/components/layout/Wraper";
import Navigation from "@/components/sections/Navigation";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Wraper>
        <Navigation/>
      </Wraper>
    </>
  );
}
