import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Wraper from "@/components/layout/Wraper";
import Navigation from "@/components/sections/Navigation";
import Header from "@/components/sections/Header";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Lobster&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=The+Nautigal:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
        <Navigation/>
        <Header/>
    </>
  );
}
